Update deploy-new.yml

diff --git a/.github/workflows/deploy-new.yml b/.github/workflows/deploy-new.yml
--- a/.github/workflows/deploy-new.yml
+++ b/.github/workflows/deploy-new.yml
@@ -20,6 +20,12 @@ jobs:
     environment: Production
 
     steps:
+      - name: Validate
+        if: ${{!fromJson(vars.CLOUDFRONT_IDS)[github.event.inputs.facility]}}
+        run: |
+          echo "Missing Facility Id in Config"
+          exit 1
+
       - name: Checkout
         uses: actions/checkout@v2
 
